version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "rust-module/"
    schedule:
      interval: "daily"
      time: "00:00"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
